web:
  build: .
  command: node index-db.js
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    MYSQL_DATABASE: killabayte_app
    MYSQL_USER: killabayte
    MYSQL_PASSWORD: GH34qw12
    MYSQL_HOST: db
db:
  image: orchardup/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: killabayte_app
    MYSQL_USER: killabayte
    MYSQL_PASSWORD: GH34qw12
